CREATE DATABASE IF NOT EXISTS demo;
CREATE USER 'root'@'54.122.229.185' IDENTIFIED BY 'root@@123';
GRANT ALL PRIVILEGES ON demo.* TO 'root'@'54.122.229.185';

USE demo;

CREATE TABLE IF NOT EXISTS employee.entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,   
  address TEXT  NOT NULL
);
